language: java
jdk:
  - oraclejdk8

before_install:
  - mysql -e 'CREATE DATABASE testSystem;'
  - mysql -e 'CREATE USER 'user' IDENTIFIED BY 'password';'
  - mysql -e 'GRANT ALL PRIVILEGES ON testSystem.* TO 'user';'

services:
  - mysql

script:
  - ./gradlew build